### ISSUE TITLE
Guide for how to running detect_event ???!!!!!!

### ISSUE THREAD

**Issue by behnazeslami** [AdrienGuille/pyMABED#4]
@AdrienGuille 
Hi,
Based on your read me link in your pyMABED, I've been creating a csv file and fed it as an input file but I have a big problem nothing happen. I've been attached my csv file and the screen shot of my output.
Please help me more.
![untitled](https://user-images.githubusercontent.com/3388317/35744684-39b14802-0856-11e8-9af2-d4fb9bbaa718.png)

My Twitter .csv file : [Book2.zip](https://github.com/AdrienGuille/pyMABED/files/1690111/Book2.zip)

**Comment by AdrienGuille** [comment]
Hi,

You're trying to extract events with a 30-minute window from a collection of (only) 5234 tweets. Thus, you have more time-slices (14689) than tweets. By definition, MABED can't operate on these extremely sparse data. You need to configure a larger window, like a week, instead of 30 minutes.
Everything you need to know to configure pyMABED correctly is in the [README.md](https://github.com/AdrienGuille/pyMABED/blob/master/README.md).
