### ISSUE TITLE
Running pyMabed for detecting event but getting Error in time_slice???

### ISSUE THREAD

**Issue by behnazeslami** [AdrienGuille/pyMABED#5]
@AdrienGuille 
**Hi Mr.Guille,**

Based on your response in this issue https://github.com/AdrienGuille/pyMABED/issues/4, I've been created a dataset with multiple range of date with their tweets but again I've got error??

Please guide me for solving this issue.

**Image of my error:**
![photo_2018-02-18_16-05-58](https://user-images.githubusercontent.com/3388317/36351958-44236d70-14c6-11e8-83f7-5abd1dbb6fbf.jpg)

**Also my .csv dataset :**

[input-data.txt](https://github.com/AdrienGuille/pyMABED/files/1734710/input-data.txt)
[input-data.zip](https://github.com/AdrienGuille/pyMABED/files/1734711/input-data.zip)

Thanks.

**Comment by AdrienGuille** [comment]
Hi,

I'm sorry but I can't help you. Your issue is related to your data, not the implementation of MABED. I can see from your screen capture that you still have more time slices than tweets, which makes no sense for MABED. Also, a time slice should contain at least a thousand tweets, so that word frequency can be estimated correctly. If you can't gather more data than what you have now, then you won't be able to run MABED. I recommend trying other methods, even though I'm not aware of any event detection method that would perform well on these data.

Adrien
